# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: sanchimi <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/02/20 15:32:53 by sanchimi          #+#    #+#              #
#    Updated: 2020/02/20 17:32:08 by sanchimi         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME=ft_dislay_file

SRCS=scrs/ft_*c


all:
		gcc $(SCRS)	-o $(NAME)

clean:
		/bin/rm -f *.o

fclean:	clean
		/bin/rm -f $(NAME)

re:	clean all
